### ISSUE TITLE
read this

### ISSUE THREAD

**Issue by gizmo75rus** [aeone1/Library#1]
Hi bro ))  I am the author of the test task. You went the wrong way, added binary database files to the project.  One of the conditions was the presence of MSSQL scripts in the project: 1. script for creating the database and 2. script for filling out the test data set of the database. Just do it.

**Comment by aeone1** [comment]
Hey bro) Thank you. Already working on it.

**Comment by aeone1** [comment]
Hi bro))) I have added some SQL scripts for creation of tables and some Post Deployment scripts for adding data to those tables. I am currently working on running them from the C# application. Any feedback would be greatly appreciated.)) Thanks.

**Comment by aeone1** [comment]
Its done and uploaded to RogaCo_LibraryManagement repo.
